import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const viewerDir = path.join(repoRoot, "src", "viewer");
const generatedDir = path.join(repoRoot, "src", "generated");
const outputPath = path.join(generatedDir, "viewerBundle.ts");

const templatePath = path.join(viewerDir, "template.html");
const stylesPath = path.join(viewerDir, "styles.css");
const entryPath = path.join(viewerDir, "index.ts");

const template = await readFile(templatePath, "utf8");
const styles = await readFile(stylesPath, "utf8");
const buildResult = await esbuild.build({
	entryPoints: [entryPath],
	bundle: true,
	format: "esm",
	platform: "browser",
	target: "es2022",
	write: false,
	legalComments: "none",
});

const bundledScript = buildResult.outputFiles[0].text.replaceAll(
	"</script>",
	"<\\/script>",
);
const finalTemplate = template
	.replace("__CIMAL_VIEWER_STYLES__", styles.trim())
	.replace("__CIMAL_VIEWER_SCRIPT__", bundledScript.trim());

const generatedSource = `// Generated by scripts/build-viewer.mjs. Do not edit by hand.
export const VIEWER_DOCUMENT_TEMPLATE = ${JSON.stringify(finalTemplate)};
`;

await mkdir(generatedDir, { recursive: true });
await writeFile(outputPath, generatedSource, "utf8");
